name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run dev --if-present &
      env:
        HOST: 0.0.0.0
    - name: Show workspace directory
      run: ls -R ${{ github.workspace }}
    - name: Close server
      run: kill $(lsof -t -i:3000)
